# Generated by Django 3.2.5 on 2021-07-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210724_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
