# Generated by Django 3.2.5 on 2021-07-25 16:32

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.carousel_upload_to)),
                ('header', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
