# Generated by Django 3.2.5 on 2021-07-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kutub.davlat')),
            ],
        ),
        migrations.CreateModel(
            name='Kutubxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kutub.davlat')),
                ('tuman', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='kutub.tuman')),
            ],
        ),
    ]
